### ISSUE TITLE
i know i'm asking for a lot but any plans for http2? on the roadmap?

### ISSUE THREAD

**Issue by ultperf** [sysprog21/khttpd#11]
i know i'm asking for a lot but any plans for http2? on the roadmap?

if so, when can we expect that to happen?

**Comment by jserv** [comment]
This project was intentionally a minimalist web server implemented as a Linux kernel module, meaning that only HTTP 1.1 would be supported by it. HTTP/2 or HTTP/3 is definitely harder for current codebase, and I have no plan for such work.
